
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun May 16 12:27:33 CDT 2021
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int INVITE = 17;
  public static final int LKEY = 5;
  public static final int EQUALBIGGER = 34;
  public static final int LBRACKET = 30;
  public static final int CHAT = 14;
  public static final int RENAME = 21;
  public static final int CONST = 12;
  public static final int MEMBERS = 22;
  public static final int LPAREN = 3;
  public static final int SEMI = 2;
  public static final int LESS = 32;
  public static final int FOR = 10;
  public static final int RPAREN = 4;
  public static final int AND = 25;
  public static final int IN = 11;
  public static final int OR = 26;
  public static final int DIFFERENT = 28;
  public static final int ASSIGN = 29;
  public static final int IF = 8;
  public static final int ARCHIVE = 19;
  public static final int ID = 37;
  public static final int EOF = 0;
  public static final int PURPOSE = 18;
  public static final int RBRACKET = 31;
  public static final int CONVERSATION = 13;
  public static final int EQUAL = 27;
  public static final int TRUE = 23;
  public static final int RKEY = 6;
  public static final int error = 1;
  public static final int BIGGER = 33;
  public static final int KICK = 20;
  public static final int UNION = 7;
  public static final int ELSE = 9;
  public static final int MESSAGE = 15;
  public static final int CREATE = 16;
  public static final int LET = 36;
  public static final int STRING = 38;
  public static final int EQUALLESSER = 35;
  public static final int FALSE = 24;
}

